[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = "Shougo/neosnippet"

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
 
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-jp/vim-cpp'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo ='tyru/open-browser.vim'

