
#colorschemes
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

#status line
[[plugins]]
repo = 'itchyny/lightline.vim'

#auto completion
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = "Shougo/neosnippet"

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#show indent
[[plugins]]
repo = 'Yggdroot/indentLine'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo ='tyru/open-browser.vim'

#make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'
