#colorschemes
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-fugitive.vim
'''

#surround
[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-surround.vim
'''

#file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

#united interface
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/denite.vim
'''

#status line
[[plugins]]
repo = 'itchyny/lightline.vim'

#bracket
[[plugins]]
repo ='cohama/lexima.vim'

#indent
[[plugins]]
repo = 'Yggdroot/indentLine'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-markdown.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  source ~/dotfiles/nvim/plugins/previm.vim
'''

[[plugins]]
repo ='tyru/open-browser.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/open-browser.vim
'''

#LaTeX
[[plugins]]
repo = 'lervag/vim-latex'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-latex.vim
'''
on_ft =['tex','plaintex']

#make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/seiya.vim
'''

#complettion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

hook_add = '''
  source ~/dotfiles/nvim/plugins/deoplete.vim
'''
#snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/neosnippet.vim
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#LSP
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = './install.sh'
hook_add = '''
source ~/dotfiles/nvim/plugins/LanguageClient.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#test
[[plugins]]
repo = 'Kotaro7750/changememo'
