# ----------
# Colorscheme and Syntax highlight
# ----------
[[plugins]]
repo = 'cocopon/pgmnt.vim'
rev = 'main'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'Kotaro7750/nagomi'

# ----------
# Visual
# ----------

# Cool status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/dotfiles/nvim/plugins/lightline.vim'

# Make indent visible
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'lua require("plugin-configs/indentLine")'

# Make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = 'lua require("plugin-configs/seiya")'

# Add file type icon
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# Add file type icon into telescope.nvim
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
hook_add = 'lua require("plugin-configs/nvim-web-devicons")'

# ----------
# Search
# ----------

# Highlight searching result and substitute preview
[[plugins]]
repo = 'markonm/traces.vim'

# ----------
# Completion
# ----------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

hook_add = 'lua require("plugin-configs/deoplete")'

# Lua base completion engine
#[[plugins]]
#repo = 'hrsh7th/nvim-cmp'

# Auto insert corresponding parentheses
[[plugins]]
repo ='cohama/lexima.vim'

# Display function signature
[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'lua require("plugin-configs/echodoc")'

# Insert snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = 'lua require("plugin-configs/neosnippet")'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# Standard snippets for neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# ----------
# Git
# ----------
# Show diff marker in column
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Git operation via vim
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'lua require("plugin-configs/vim-fugitive")'

# ----------
# Interface
# ----------

# File tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'lua require("plugin-configs/nerdtree")'

# United interface
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/dotfiles/nvim/plugins/denite.vim'

# Add clip board into denite
[[plugins]]
repo = 'Kotaro7750/denite-clipy'
hook_add = 'lua require("plugin-configs/denite-clipy")'

# Fuzzy finder
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = 'lua require("plugin-configs/telescope")'

# ----------
# Language specific
# ----------

# Markdown in vim
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'lua require("plugin-configs/vim-markdown")'

# Online markdown preview
[[plugins]]
repo = 'previm/previm'
hook_add = 'lua require("plugin-configs/previm")'

# LaTeX in vim
[[plugins]]
repo = 'lervag/vimtex'
hook_add = 'source ~/dotfiles/nvim/plugins/vimtex.vim'
on_ft =['tex','plaintex']

# Wrapper of NeoVim-Lua API
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# ----------
# LSP
# ----------

# LSP client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = './install.sh'
hook_add = 'source ~/dotfiles/nvim/plugins/LanguageClient.vim'

# File type utility
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# build-in LSP client
#[[plugins]]
#repo = 'neovim/nvim-lspconfig'
#hook_add = 'lua require("plugin-configs/nvim-lspconfig")'

# ----------
# Extend basic function
# ----------

# Comment in a simple way
[[plugins]]
repo = 'tpope/vim-commentary'

# Easily operate parentheses
[[plugins]]
repo = 'tpope/vim-surround'

# Easily make table
[[plugins]]
repo = 'mattn/vim-maketable'

# ----------
# Cooperate with other program
# ----------

# Open URI in browser
[[plugins]]
repo ='tyru/open-browser.vim'
hook_add = 'lua require("plugin-configs/open-browser")'

# Debug by vim
[[plugins]]
repo = 'sakhnik/nvim-gdb'
hook_add = 'lua require("plugin-configs/nvim-gdb")'

# Memo in vim
[[plugins]]
repo = 'Kotaro7750/vim1cache'
hook_add = 'lua require("plugin-configs/vim1cache")'
