#colorschemes
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

#united interface
[[plugins]]
repo = 'Shougo/denite.nvim'

#status line
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo ='cohama/lexima.vim'

#asynchronous syntax check
[[plugins]]
repo='w0rp/ale'

#auto completion
[[plugins]]
repo='zchee/deoplete-clang'

[[plugins]]
repo='zchee/deoplete-jedi'

[[plugins]]
repo = 'vim-jp/vim-cpp'

#snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo ='tyru/open-browser.vim'

#make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'
