#colorschemes
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

#file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

#united interface
[[plugins]]
repo = 'Shougo/denite.nvim'

#status line
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo ='cohama/lexima.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo ='tyru/open-browser.vim'

#LaTeX
[[plugins]]
repo = 'lervag/vim-latex'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/vim-latex.vim
'''
on_ft =['tex','plaintex']

#make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'

#snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/neosnippet.vim
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#LSP
#[[plugins]]
#repo='w0rp/ale'
#
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#hook_add = '''
#  source ~/dotfiles/nvim/rc/plugins/asyncomplete.vim
#'''
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
#hook_add='''
#  source ~/dotfiles/nvim/rc/plugins/asyncomplete-neosnippet.vim
#'''
#
##language 
#[[plugins]]
#repo = 'leafgarland/typescript-vim'
#
#[[plugins]]
#repo = 'posva/vim-vue'
#
#[[plugins]]
#repo = 'ryanolsonx/vim-lsp-python'
