#colorschemes
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

#file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

#united interface
[[plugins]]
repo = 'Shougo/denite.nvim'

#status line
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo ='cohama/lexima.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo ='tyru/open-browser.vim'

#LaTeX
[[plugins]]
repo = 'lervag/vim-latex'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/vim-latex.vim
'''
on_ft =['tex','plaintex']

#make vim transparent
[[plugins]]
repo = 'miyakogi/seiya.vim'

#complettion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/deoplete.vim
'''
#snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/neosnippet.vim
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'



#LSP
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = './install.sh'
hook_add = '''
source ~/dotfiles/nvim/rc/plugins/LanguageClient.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#test
[[plugins]]
repo = 'Kotaro7750/changememo'
