{ pkgs, ... }:

let
  autoGeneratedPreamble = (import ./preamble.nix).autoGeneratedPreamble;
  nvimPython = pkgs.python314.withPackages (ps: with ps; [
    pynvim
  ]);
  nvimNode = pkgs.buildEnv {
    name = "nvim-node";
    paths = [
      pkgs.nodejs_24
      pkgs.yarn # for neovim healthcheck
      pkgs.neovim-node-client
    ];
  };
in
{
  home.packages = [
    pkgs.neovim-unwrapped
  ];

  xdg.configFile."nvim/providers.lua".source = pkgs.replaceVars ./nvim/providers.lua.in {
    autoGeneratedPreamble = autoGeneratedPreamble;
    nvimPython = nvimPython;
    nvimNode = nvimNode;
  };

  xdg.configFile."nvim/init.lua".source = pkgs.replaceVars ./nvim/bootstrap.lua.in {
    autoGeneratedPreamble = autoGeneratedPreamble;
  };
}
