{ pkgs, ... }:

let
  autoGeneratedPreamble = (import ./preamble.nix).autoGeneratedPreamble;
in

{
  home.packages = [
    pkgs.zsh
    pkgs.starship
    pkgs.peco
  ];

  home.file.".zshrc".text = ''
    # ${autoGeneratedPreamble}
    #
    # cf. https://nix-community.github.io/home-manager/index.xhtml#_why_are_the_session_variables_not_set
    . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

    [ -f "$DOTFILES/zsh/zshrc" ] && source "$DOTFILES/zsh/zshrc"
  '';

  xdg.configFile."zsh/zshrc".source = ../../zsh/zshrc;

  # plugins
  # zsh-completions recommends adding `.../zsh-completions/src` to `$fpath`.
  xdg.configFile."zsh/plugins/zsh-completions/src".source = "${pkgs.zsh-completions}/share/zsh/site-functions";
  xdg.configFile."zsh/plugins/zsh-autosuggestions.zsh".source = "${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh";
  xdg.configFile."zsh/plugins/zsh-syntax-highlighting.zsh".source = "${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh";

  xdg.configFile."starship.toml".source = ../../zsh/starship.toml;
}
