#Vim mode
bindkey -v

#Vim prompt
function zle-line-init zle-keymap-select {
  case $KEYMAP in
    vicmd)
    PROMPT="%F{green}[%W %T:%/]%f"$'\n'"%n@%m/%F{blue}NOR%f> "
    ;;
    main|viins)
    PROMPT="%F{green}[%W %T:%/]%f"$'\n'"%n@%m/%F{green}INS%f> "
    ;;
  esac
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

#補完機能
autoload -U compinit
compinit

autoload -Uz colors
colors

export PATH=/usr/local/bin:/usr/bin:$HOME/bin/:$PATH

#プロンプトのカスタム
PROMPT='%F{green}[%W %T:%/]%f'$'\n''%n@%m >'

XDG_CONFIG_HOME=~/.config/

#-------------------
#プラグイン
#-------------------

#-----zplug-----
source ~/.zplug/init.zsh

#プラグイン定義
zplug "zsh-users/zsh-syntax-highlighting", defer:3
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

case ${OSTYPE} in
  darwin* )
#OSによってコメントアウトを変える
    export LSCOLORS=fxgxcxdxbxegedabagacad
    alias ls='ls -G'
    ;;    
  linux* )
    #export LSCOLORS=fxgxcxdxbxegedabagacad
    #export LS_COLORS=fxgxcxdxbxegedabagacad
    eval $(dircolors ~/ls_color/dircolors-solarized/dircolors.ansi-universal)
    alias ls='ls --color'
    ;;

esac
zplug "zsh-users/zsh-completions"


#インストール
if ! zplug check --verbose; then
  printf 'Install? [y/N]: '
  if read -q; then
    echo; zplug install
  fi
fi

zplug load --verbose
