name: "init script test"

on:
  push:
    paths:
    - 'init/linux'

jobs:
  init-test:

    matrix:
      os: [ubuntu-latest,macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: init
      working-directory: ./init/linux
      run: make init
    - name: link
      working-directory: ./init/linux
      run: make link
