name: "init script test"

on:
  push:
    paths:
    - '.github/workflows/init-test.yml'
    - 'init/linux/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        script: ["./script/albert.sh", "./script/docker.sh","./script/latex.sh","./script/nvim.sh","./script/zsh.sh","./script/python/pyenv.sh"]
    
    steps:
      - uses: actions/checkout@v2
      - name: unit-test of ${{matrix.script}}
        working-directory: ./init/linux
        run: ${{matrix.script}}
  
  init-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      working-directory: ./init/linux
      run: make init
    - name: link
      working-directory: ./init/linux
      run: make link
