name: "init script test"

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      working-directory: ./init/linux
      run: make init
    - name: link
      working-directory: ./init/linux
      run: make link
